AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  AuthLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: AuthLayer
      Description: AuthLayer
      Content:
        S3Bucket: artifactoutbucket
        S3Key: aws_auth.zip
      CompatibleRuntimes:
        - python3.12
  PdftotxtS3:
    Type: AWS::S3::Bucket
    DependsOn: ExampleInvokePermission
    Properties:
      BucketName: txtbucketstage2
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: txt
            Function: !GetAtt [ uploadtosearch, Arn]
  ExampleInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: uploadtosearch
    Properties:
      FunctionName:
        Fn::GetAtt:
          - uploadtosearch
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::txtbucketstage2  
  uploadtosearch:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.12
      CodeUri: .
      Description: 'uploadtosearch lambda'
      MemorySize: 512
      Timeout: 120
      Role: 'arn:aws:iam::637423317527:role/multirolelamda'
      Layers:
        - !Ref AuthLayer
